### ISSUE TITLE
java.lang.IllegalStateException: Failed to load ApplicationContext

### ISSUE THREAD

**Issue by NCookies** [NCookies/spring-practice#2]
빌드 성공 확인 이후 build.yml 파일을 정리하다가 발생한 이슈
디비 설정 관련 문제 같은데 천천히 확인해보면서 원인을 찾아보자

    ***************************
    APPLICATION FAILED TO START
    ***************************

    Description:

    Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

    Reason: Failed to determine a suitable driver class

    Action:

    Consider the following:
    	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
    	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

    2022-11-04 11:10:56.629 ERROR 2738 --- [    Test worker] o.s.***.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.***.context.web.ServletTestExecutionListener@1734f68] to prepare *** instance [com.ncookie.springpractice.SpringPracticeApplicationTests@3b42121d]

    java.lang.IllegalStateException: Failed to load ApplicationContext
    	at org.springframework.***.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:98) ~[spring-***-5.3.23.jar:5.3.23]
    	at org.springframework.***.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124) ~[spring-***-5.3.23.jar:5.3.23]
    	at org.springframework.***.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190) ~[spring-***-5.3.23.jar:5.3.23]
    	at org.springframework.***.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132) ~[spring-***-5.3.23.jar:5.3.23]
    	at org.springframework.***.context.TestContextManager.prepareTestInstance(TestContextManager.java:248) ~[spring-***-5.3.23.jar:5.3.23]
    	at org.springframework.***.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138) ~[spring-***-5.3.23.jar:5.3.23]
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$8(ClassBasedTestDescriptor.java:363) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:368) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
    	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$9(ClassBasedTestDescriptor.java:363) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
    	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
    	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
    	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
    	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
    	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
    	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[na:na]
    	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[na:na]
    	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[na:na]
    	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
...

**Comment by NCookies** [comment]
우선 깃헙 SECURITY의 디비 설정값과 mysql 액션 부분을 확인해보자

**Comment by NCookies** [comment]
Secrets의 프로퍼티 이름을 변경해놓고 yml 파일에 반영하지 않았었음
